/** Auto-generated by fork-avure.ps1 */

export const APP_PREFIX = "avure:";
export const APP_NAME = "Avure";

export const STORAGE_KEYS = {
  FILTERS_SHARED: `${APP_PREFIX}filters:shared`,
  FILTERS_PACKHOUSE_BREAKDOWN: `${APP_PREFIX}filters:packhouse:breakdown`,
  FILTERS_PACKHOUSE_PERFORMANCE: `${APP_PREFIX}filters:packhouse:performance`,
  FILTERS_PRICE_WISE: `${APP_PREFIX}filters:price-wise`,
  SESSION_CACHE: `${APP_PREFIX}session:cache`,
};