<#
.SYNOPSIS
    Clone the current Vera Insights workspace into a new Avure fork with fresh configuration scaffolding.

.DESCRIPTION
    * Copies the entire vera-insights directory to a sibling avure directory.
    * Removes existing git history from the fork and re-initialises a clean repository.
    * Generates a `.env.local.template` file for the new Firebase credentials.
    * Creates a lightweight configuration module (`lib/config.ts`) with per-app prefixes.
    * Updates `package.json` and `firebase.json` with the new app name (if present).
    * Produces a VS Code workspace linking both projects.
    * Writes a migration checklist to guide remaining manual steps.

.NOTES
    Run this script from the parent folder that contains the vera-insights directory.
    Example:
        PS> cd d:\projects\clients\optimalx-smart-business
        PS> .\vera-insights\scripts\fork-avure.ps1
#>

param (
    [string]$SourceDir = "vera-insights",
    [string]$TargetDir = "avure",
    [string]$NewAppName = "avure",
    [string]$StoragePrefix = "avure:" ,
    [switch]$Force
)

function Write-Section {
    param([string]$Message, [ConsoleColor]$Color = 'Yellow')
    Write-Host "[+] $Message" -ForegroundColor $Color
}

function Assert-DirectoryExists {
    param([string]$Path)
    if (-not (Test-Path $Path)) {
        throw "Directory not found: $Path"
    }
}

function Ensure-CleanTarget {
    param([string]$Path)
    if (Test-Path $Path) {
        if (-not $Force) {
            $answer = Read-Host "Target '$Path' already exists. Overwrite? (y/N)"
            if ($answer -ne 'y' -and $answer -ne 'Y') {
                throw "Aborted by user."
            }
        }
        Remove-Item -Recurse -Force $Path
    }
}

$root = Get-Location
Assert-DirectoryExists -Path (Join-Path $root $SourceDir)
Ensure-CleanTarget -Path (Join-Path $root $TargetDir)

Write-Section "Copying $SourceDir -> $TargetDir"
Copy-Item -Recurse -Force -Path (Join-Path $root $SourceDir) -Destination (Join-Path $root $TargetDir)

Push-Location (Join-Path $root $TargetDir)
try {
    Write-Section "Resetting git repository" 'Cyan'
    if (Test-Path .git) { Remove-Item -Recurse -Force .git }
    git init | Out-Null

    Write-Section "Updating package.json name" 'Cyan'
    if (Test-Path package.json) {
        (Get-Content package.json) -replace '"name":\s*"[^"]+"', '"name": "' + $NewAppName + '"' | Set-Content package.json -Encoding UTF8
    }

    Write-Section "Creating .env.local.template" 'Cyan'
    $envTemplate = @"
# Firebase configuration for Avure (COPY & RENAME to .env.local)
NEXT_PUBLIC_FIREBASE_API_KEY=
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NewAppName}.firebaseapp.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NewAppName}
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NewAppName}.appspot.com
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=
NEXT_PUBLIC_FIREBASE_APP_ID=
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=

NEXT_PUBLIC_APP_NAME=Avure
"@
    Set-Content -Path ".env.local.template" -Value $envTemplate -Encoding UTF8
    if (Test-Path ".env.local") { Rename-Item ".env.local" ".env.local.backup" }

    Write-Section "Generating lib/config.ts" 'Cyan'
    $configModule = @"
/** Auto-generated by fork-avure.ps1 */

export const APP_PREFIX = "${StoragePrefix}";
export const APP_NAME = "Avure";

export const STORAGE_KEYS = {
  FILTERS_SHARED: `${APP_PREFIX}filters:shared`,
  FILTERS_PACKHOUSE_BREAKDOWN: `${APP_PREFIX}filters:packhouse:breakdown`,
  FILTERS_PACKHOUSE_PERFORMANCE: `${APP_PREFIX}filters:packhouse:performance`,
  FILTERS_PRICE_WISE: `${APP_PREFIX}filters:price-wise`,
  SESSION_CACHE: `${APP_PREFIX}session:cache`,
};
"@
    $libDir = Join-Path $PWD 'lib'
    if (-not (Test-Path $libDir)) { New-Item -ItemType Directory -Path $libDir | Out-Null }
    Set-Content -Path (Join-Path $libDir 'config.ts') -Value $configModule -Encoding UTF8

    Write-Section "Updating firebase.json (if present)" 'Cyan'
    if (Test-Path firebase.json) {
        (Get-Content firebase.json) -replace '"site":\s*"[^"]+"', '"site": "' + $NewAppName + '"' | Set-Content firebase.json -Encoding UTF8
    }

    Write-Section "Writing migration checklist" 'Cyan'
    $checklist = @"
# Avure Migration Checklist

## ✅ Immediate Tasks
- [ ] Create new Firebase project and update `.env.local`
- [ ] Install dependencies: `npm install`
- [ ] Run dev server on alternate port: `npm run dev -- -p 3001`
- [ ] Replace sessionStorage/localStorage keys with `STORAGE_KEYS`
- [ ] Configure git remote: `git remote add origin <your-repo>`
- [ ] Initial commit: `git add . && git commit -m "Initial Avure fork"`

## 🏗️ Optional Follow-ups
- [ ] Update branding assets (logos, colors)
- [ ] Review module access rules
- [ ] Verify Firebase security rules
- [ ] Configure deployment pipeline (Firebase Hosting / Vercel / etc.)

"@
    Set-Content -Path "MIGRATION_CHECKLIST.md" -Value $checklist -Encoding UTF8
}
finally {
    Pop-Location
}

Write-Section "Creating VS Code multi-root workspace" 'Cyan'
$workspace = @"
{
  "folders": [
    { "path": "$SourceDir", "name": "Vera Insights" },
    { "path": "$TargetDir", "name": "Avure" }
  ],
  "settings": {
    "files.exclude": { "**/node_modules": true, "**/.next": true },
    "search.exclude": { "**/node_modules": true, "**/.next": true }
  }
}
"@
Set-Content -Path (Join-Path $root "insights-workspace.code-workspace") -Value $workspace -Encoding UTF8

Write-Section "Fork complete!" 'Green'
Write-Host "Next steps:" -ForegroundColor Green
Write-Host "  1. cd $TargetDir" -ForegroundColor Green
Write-Host "  2. Review MIGRATION_CHECKLIST.md" -ForegroundColor Green
Write-Host "  3. Copy .env.local.template → .env.local with new Firebase credentials" -ForegroundColor Green
Write-Host "  4. npm install" -ForegroundColor Green
Write-Host "  5. git remote add origin <new-repo-url>" -ForegroundColor Green
